// Auto-generated blur placeholders for carousel images
export const blurPlaceholders: Record<string, string> = {
  '/products/aerocoolers/ECO_FRESCO.webp': 'data:image/webp;base64,UklGRn4AAABXRUJQVlA4IHIAAABwAgCdASoQABAAA4BaJbACdAEUr/N2OtUiQuAAAP61LD+LKwDdQ5ZARZ56B6DdJ77HdC0LEF8ivToqC4XsRCbQZzd5JcHGWXz6P6xqLCsV8BnVeHzZOKZxGzPxX6wh0Zjalr4RfqOJlu6zDSkzt3qQAAA=',
  '/products/aerocoolers/IMG_4064.webp': 'data:image/webp;base64,UklGRngAAABXRUJQVlA4IGwAAABwAgCdASoMABAAA4BaJYwCdMn8BKrIqqQN57kAAP7qVoqtP+JMSayNskACo4pEq+1P1jCYSQKBHPdjVzipD/YsGWNIJTeVIPuxAL1GXEJU7ACIjTWQq1NtSq+di4i1Z2uk9iCJkEbjM8fQAAA=',
  '/products/aerocoolers/TURBO_FRIO.webp': 'data:image/webp;base64,UklGRmgAAABXRUJQVlA4IFwAAAAQAgCdASoQABAAA4BaJbACdAERH9V/DHYAAP7x3pNUhR9R+QMmsiziLrNCU/TFhYy7OIWfwv++QxVOHFtdidZ/emJ6a4GSLSCtkuv0+l4fX3LEQnLvRzT7HtcAAA==',
  '/products/aerocoolers/IMG_1038_copy.jpg': 'data:image/webp;base64,UklGRmYAAABXRUJQVlA4IFoAAADwAQCdASoQAAwAA4BaJZwAAuPcERU04AAAy0/UhhM0FkCJ8oYDD3itUf/Syq2YYjnZRLoUIvYbkfFuV383fZmY8WD+iKAG5MFXOGOkvsktk2AKTpxfo4cAAAA=',
  '/products/aerocoolers/ecoyturbo01.webp': 'data:image/webp;base64,UklGRmIAAABXRUJQVlA4IFYAAAAQAgCdASoMABAAA4BaJZQAAxU2Vov55BgAAPR2/GveperYq6gXsXZrBVzn/lnlqGUImPl+MBB4OPheJVeXejX277d0K9p1MSMa4+3zuFGjZGAcC1QAAA==',
  '/products/aerocoolers/ecoyturbo02.webp': 'data:image/webp;base64,UklGRloAAABXRUJQVlA4IE4AAADwAQCdASoMABAAA4BaJZwAAugtZzo8n0gA/sXd7gqomJiIwafxxDkjZK6uqAiFBfpIJUqc6f+1h9vJ1AvHwPwACxn5T4wVZvqZCgshIAA=',
  '/products/aerocoolers/ecoyturbo03.webp': 'data:image/webp;base64,UklGRlAAAABXRUJQVlA4IEQAAAAQAgCdASoMABAAA4BaJQBOj+ACa0cPhggAAP2XNf3Q99pVmrr9f/ui+CCPSCr+sd7di30+by6bMKBIPrJNKnmg7IAAAA==',
  '/products/aerocoolers/turbo01.webp': 'data:image/webp;base64,UklGRmQAAABXRUJQVlA4IFgAAADwAQCdASoMABAAA4BaJZACdAEOzrJtO+AA/uk1+JWl2nPetguGqewAx50wydmidBmHXoh3CqlUijyuViCFr/x5ILSDRNTHEvULTnzKzy6HnfYS0xZI0wAA',
  '/products/aerocoolers/IMG_1251.webp': 'data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAAAQAgCdASoMABAAA4BaJZACdADcHhkhdV+AAP6jO3JQPvR6jEzQl55QoQYpWeSTRKRJ5YUAnE/ngfCIzA9CE4+1A7NyUX0zHM/8w9R5pbR5AAAA',
  '/products/calentones/cal-01.webp': 'data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAAAQAgCdASoLABAAA4BaJYwC7AEUnEF8y2gAAP7wj+E73ELPDJ/EEtNbLbna45C65io82ou22xoe5cSEpeVmXPpmwNs6vRkF8hMaWYtUO5FYCAAA',
  '/products/calentones/04.webp': 'data:image/webp;base64,UklGRmQAAABXRUJQVlA4IFgAAAAwAgCdASoMABAAA4BaJZQCsAEDe7PJoJkliAD5SqJy1xi7OTI+RntfDM3u98ImgsW1jhzMiPgdjJ5tJalI6nP7MHC1kv9DOfeBAQsbZRSrfSN+oHEA9VAA',
  '/products/calentones/06.webp': 'data:image/webp;base64,UklGRloAAABXRUJQVlA4IE4AAADwAQCdASoMABAAA4BaJQBYdiIaNvxA/gAA/mbDgXvPwSNo1uEROdwiwNkYZixEYbrYGF1B8ijl3GWFKMaw+tVUgOlvlAc+Ja/m//GAAAA=',
  '/products/calentones/02.webp': 'data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAADQAQCdASoJABAAA4BaJQBOgCHXRup3AAD3pejLhG7QzKpyBM/NWhwf4DBseeOZnBEebpL6tyZpRfpuESJaEJIe7HEzWuFIHjM4AA==',
  '/products/calentones/03.webp': 'data:image/webp;base64,UklGRmQAAABXRUJQVlA4IFgAAADQAQCdASoJABAAA4BaJQBOgBuMUgghAAD+9e9Nh4qwb3V72/gfncYhrnWIJFSlovNxYnGkscPWR1/fcH/tlntkR6x8H7cShf8tuer+MuSp3F54TKz0AAAA',
  '/products/calentones/05.webp': 'data:image/webp;base64,UklGRmoAAABXRUJQVlA4IF4AAACwAQCdASoMABAAA4BaJYwAAluxBlA4AMtPskEs5OBDNoxEmjHpDfZ4359ivvgswMCC9jVD3uaEMB4AOu/4xKrL3SrN8JWWXwqGwlCefihRRNUWklWt1jLn01IDwAAA',
  '/products/calentones/07.webp': 'data:image/webp;base64,UklGRnAAAABXRUJQVlA4IGQAAABwAgCdASoMABAAA4BaJZQCdAYulbMjwO9LA/8AAP6tJEGMPzmdJY1bl9Le+mkfPb8ssVfdZJUpXLWRD0jHPlC07FQjST6LNCPRgNDnW4VxeZmLjq0oxsxsT4Mo/+CECGAVbQAA',
  '/products/calentones/08.webp': 'data:image/webp;base64,UklGRmwAAABXRUJQVlA4IGAAAADQAQCdASoMABAAA4BaJQBOgBZSpz4+AADOMtWuvBFryE6A9KuRi2GM3Dzr/wqH38iKm4D+fKpo3NgYrGVj4w0e4nvhTtCSSR8VHgLMWEp50ts+pOGdBdfu+hLzc7+AAAA=',
  '/products/calentones/10.webp': 'data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAADQAQCdASoJABAAA4BaJZwAD46wZaU4AADJd/sU0Q/JyE+4RgCgRDdG2cSzkt0Y/Tgb9cxy7Lz80taenoNi7T7oz8D0lczHjQX4vSrS49RDIE+5eAA=',
  '/products/calentones/11.webp': 'data:image/webp;base64,UklGRm4AAABXRUJQVlA4IGIAAAAQAgCdASoMABAAA4BaJZwAD5JtJhRuxGAAAP7vrOvJ7A216CV20+X3XTyIHghXpy+yly/AosgP9kKjeL8q5Nfgsc1B5A3XScyYwDrqU1d7wgas11QanC+p0+c70EIx0CAAAA==',
};
